# Generated by Django 5.2.3 on 2025-06-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('anuncio', 'Anuncio'), ('personal', 'Mensaje Personal')], max_length=50)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('leido', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notificaciones_receptor_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
    ]
