# Generated by Django 5.2.3 on 2026-04-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('archivada', 'Archivada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='objeto_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='objeto_tipo',
            field=models.CharField(blank=True, help_text='Ej: pago, recibo, mensualidad, gasto_extra', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notificaciones_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('recordatorio', 'Recordatorio'), ('anuncio', 'Anuncio'), ('personal', 'Mensaje Personal'), ('sistema', 'Sistema')], max_length=50),
        ),
    ]
