# Generated by Django 5.2.3 on 2025-06-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], max_length=20)),
                ('fecha_pago', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contratos.mensualidad')),
                ('validado_por', models.ForeignKey(blank=True, db_column='validado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='PagoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_billete', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.pago')),
            ],
            options={
                'db_table': 'pagos_efectivo',
            },
        ),
        migrations.CreateModel(
            name='PagoTransferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_destino', models.CharField(max_length=100)),
                ('cuenta_destino', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=100)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comprobante_img', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.pago')),
            ],
            options={
                'db_table': 'pagos_transferencias',
            },
        ),
    ]
