# Generated by Django 5.2.3 on 2025-06-15 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_mensualidad_saldo_pendiente'),
        ('gastos', '0002_gastoextra_saldo_pendiente'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recibos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recibos',
            },
        ),
        migrations.CreateModel(
            name='ReciboGastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_extra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gastos.gastoextra')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='pagos.recibo')),
            ],
            options={
                'db_table': 'recibo_gastos_extra',
            },
        ),
        migrations.CreateModel(
            name='ReciboMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contratos.mensualidad')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='pagos.recibo')),
            ],
            options={
                'db_table': 'recibo_mensualidades',
            },
        ),
    ]
