# Generated by Django 5.2.3 on 2025-06-16 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_recibo_recibogastoextra_recibomensualidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='validado_por',
            field=models.ForeignKey(blank=True, db_column='validado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos_validados', to=settings.AUTH_USER_MODEL),
        ),
    ]
