# Generated by Django 5.2.3 on 2025-06-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_mensualidad_saldo_pendiente'),
        ('gastos', '0002_gastoextra_saldo_pendiente'),
        ('pagos', '0003_pago_usuario_alter_pago_validado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='gasto_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gastos.gastoextra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='mensualidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contratos.mensualidad'),
        ),
    ]
