# Generated by Django 5.2.3 on 2025-06-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_mensualidad_saldo_pendiente'),
        ('gastos', '0002_gastoextra_saldo_pendiente'),
        ('pagos', '0004_pago_gasto_extra_alter_pago_mensualidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='gasto_extra',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='mensualidad',
        ),
        migrations.CreateModel(
            name='PagoGastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.gastoextra')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pagados', to='pagos.pago')),
            ],
            options={
                'db_table': 'pagos_gastos_extra',
                'unique_together': {('pago', 'gasto_extra')},
            },
        ),
        migrations.CreateModel(
            name='PagoMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.mensualidad')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades_pagadas', to='pagos.pago')),
            ],
            options={
                'db_table': 'pagos_mensualidades',
                'unique_together': {('pago', 'mensualidad')},
            },
        ),
    ]
