# Generated by Django 5.2.3 on 2025-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_remove_pago_gasto_extra_remove_pago_mensualidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=20),
        ),
    ]
