# Generated by Django 5.2.3 on 2025-06-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_recibo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
