# Generated by Django 5.2.3 on 2025-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_pago_monto_bs_pago_tasa_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='total_bs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
