# Generated by Django 5.2.3 on 2025-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_alter_recibo_total_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotransferencias',
            name='fecha_transferencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
