# Generated by Django 5.2.3 on 2025-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_pagotransferencias_fecha_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
    ]
