# Generated by Django 5.2.3 on 2025-07-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_alter_recibo_estado'),
        ('tasas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tasa_dia',
            field=models.ForeignKey(blank=True, help_text='Tasa del día usada para calcular este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='tasas.tasadia'),
        ),
    ]
