# Generated by Django 5.2.3 on 2025-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_pago_tasa_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='fecha_vencimiento',
        ),
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pagado', max_length=20),
        ),
    ]
