# Generated by Django 5.2.3 on 2025-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_recibo_pago_alter_pago_estado_validacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comentario_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
