# Generated by Django 5.2.3 on 2025-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasadia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='tasadia',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('anulada', 'Anulada')], default='inactiva', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='tasadia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasadia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2025-07-20'),
            preserve_default=False,
        ),
    ]
