# Generated by Django 5.2.3 on 2025-06-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioedificio',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios_asignados', to='edificios.edificio'),
        ),
        migrations.AlterField(
            model_name='usuarioedificio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edificios_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
