# Generated by Django 5.2.3 on 2025-06-20 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0002_alter_edificio_created_at_alter_edificio_updated_at'),
        ('usuarios', '0002_alter_usuarioedificio_edificio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudUsuarioEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('rol_asignado', models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('colaborador', 'Colaborador')], max_length=50, null=True)),
                ('comentario_validador', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='edificios.edificio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_usuario_edificio',
                'ordering': ['-created_at'],
            },
        ),
    ]
