# Generated by Django 5.2.3 on 2025-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitudusuarioedificio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudusuarioedificio',
            name='tipo_solicitado',
            field=models.CharField(choices=[('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario')], default='arrendatario', max_length=20),
            preserve_default=False,
        ),
    ]
