# Generated by Django 5.2.3 on 2025-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-18 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edificio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2025-06-18 00:00:00'),
            preserve_default=False,
        ),
    ]
