# Generated by Django 5.2.3 on 2025-06-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificios', '0001_initial'),
        ('tasas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_generacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edificios.apartamento')),
                ('tasa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasas.tasadia')),
            ],
            options={
                'db_table': 'gastos_extra',
            },
        ),
    ]
