# Generated by Django 5.2.3 on 2025-06-16 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_gastoextra_saldo_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoextra',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
