# Generated by Django 5.2.3 on 2025-06-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_alter_gastoextra_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoextra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], max_length=20),
        ),
    ]
