# Generated by Django 5.2.3 on 2025-06-18 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_gastoextra_fecha_vencimiento_alter_gastoextra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoextra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='fecha_generacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
