# Generated by Django 5.2.3 on 2025-06-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_alter_gastoextra_created_at_alter_gastoextra_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoextra',
            name='tasa',
        ),
    ]
