# Generated by Django 5.2.3 on 2025-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_remove_gastoextra_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoextra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
    ]
