# Generated by Django 5.2.3 on 2025-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_alter_gastoextra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoextra',
            name='comentario_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='fecha_vencimiento',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
