# Generated by Django 5.2.3 on 2025-06-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_mensualidad_created_at_and_more'),
        ('edificios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos', to='edificios.apartamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos', to=settings.AUTH_USER_MODEL),
        ),
    ]
