# Generated by Django 5.2.3 on 2025-06-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-18'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 6, 18, 13, 58, 2, 35757)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
