# Generated by Django 5.2.3 on 2025-06-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_alter_contrato_created_at_alter_contrato_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='tasa',
        ),
    ]
