# Generated by Django 5.2.3 on 2025-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_remove_mensualidad_tasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='comentario_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado'), ('anulado', 'Anulado')], max_length=20),
        ),
    ]
