# Generated by Django 5.2.3 on 2025-07-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_mensualidad_comentario_anulacion_and_more'),
        ('tasas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='monto_bs_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='tasa_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasas.tasadia'),
        ),
    ]
