# Generated by Django 5.2.3 on 2025-07-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_mensualidad_monto_bs_pagado_mensualidad_tasa_usada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='monto_bs_pagado',
        ),
        migrations.RemoveField(
            model_name='mensualidad',
            name='tasa_usada',
        ),
    ]
