# Generated by Django 5.2.3 on 2026-04-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_remove_mensualidad_monto_bs_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo_contrato_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='contratos/'),
        ),
    ]
