# Generated by Django 5.2.3 on 2025-06-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('enlace_formulario', models.TextField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, db_column='creada_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encuestas',
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace_respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('arrendatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('encuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='encuestas.encuesta')),
            ],
            options={
                'db_table': 'respuestas_encuestas',
            },
        ),
    ]
